### ISSUE TITLE
kESI forward modeling using MFEM / kESI 4 spheres 10-20

### ISSUE THREAD

**Issue by mdovgialo** [Neuroinflab/kESI#19]
Test this approach:

- take arbitrary CSD distribution as a regular grid
- resample it to mesh nodes (mesh elements size matters!)
- use GridFuctionCoefficient instead of DeltaCoefficient which is now used to simulate point current source of electrodes?

That might miss smaller dipoles, which are not sampled well enough by the mesh, we need something which defines a grid independent of the mesh...

**Comment by mdovgialo** [comment]
First result of an early (and slow) prototype:

4 spheres, CSD dipole inside, using MFEM to calculate potential. (Units are complete mish mash right now)

vaccuum

![image](https://github.com/Neuroinflab/kESI/assets/6193380/52f8c5d6-b137-4260-992f-26a654db8612)


added air:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/1f615ee0-7b87-42a4-a4d8-3f718969c8c1)

As you can see, air causes a potential drop on outer sphere surface! Is it correct?

**Comment by danek8317** [comment]
Looks great to me! The change in the potential when you add a layer of air makes sense as you add extra resistors outside. It would be interesting to see if you get back the top picture if you replace air with vacuum by setting conductivity to 0. Finally, please use the Green-Purple color code for potential to avoid confusion with CSD.

**Comment by mdovgialo** [comment]
Vacuum:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/a77e2fef-a030-457b-ab96-4004cb894693)

air:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/6c1d4d34-b06e-400a-9b12-77b1f1116e22)

air with 1e-99 conductivity, 0 is not usable, because zero causes division error (conductivities are used as 1/sigma!):

![image](https://github.com/Neuroinflab/kESI/assets/6193380/d10f2add-6225-454f-9002-7041ea899b4b)

**Comment by mdovgialo** [comment]
Trying to run tutorial again, but now with MFEM solver.

Originally potential solved for this ground truth:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/de448fa2-607f-45cc-9dbb-47c2b3619e9c)

Solved by Fenics 4 shperes in vacuum (original Kuba models):

![image](https://github.com/Neuroinflab/kESI/assets/6193380/86e9a2b0-6990-438a-ae51-1501f9d597a1)

Solved by MFEM in air:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/34f1f2b2-4372-48fa-8f2b-5a2f2c7af77e)

Solved by MFEM in vacuum:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/4df80846-2ab1-470c-99d5-c40aa892c37e)

Potentials at electrodes:

```
FENICS array([ -98.82480611, -104.38634252, -104.85733705, -104.76988544])
MFEM Air array([-1.46523184, -2.6171923 , -4.06009512, -3.89407467])
MFEM Vacuum array([-205.019364  , -209.1743933 , -210.2484358 , -210.12329201]) 
```

**Comment by mdovgialo** [comment]
MFEM forward solution in air and kCSD/kESI

Pipeline
1. Take kCSD Eignevector 0 as ground truth
2. MFEM forward solution in air
3. kCSD solution
4. kESI solution with correction of spheres in air

# GT

![image](https://github.com/Neuroinflab/kESI/assets/6193380/2abf302b-c6b8-41a1-be64-502394707ff6)

# kCSD reconstruction

![image](https://github.com/Neuroinflab/kESI/assets/6193380/3644a7dc-b3fe-4c35-9b47-e59793bad18d)

# kESI reconstruction

![image](https://github.com/Neuroinflab/kESI/assets/6193380/ef13813d-1c9b-4c11-9b6a-f4d3ad0a70f7)


# old forward model kCSD

comparing with kCSD solution  using old forward model from https://github.com/Neuroinflab/kESI/issues/17#issuecomment-2154867393 

![image](https://github.com/Neuroinflab/kESI/assets/6193380/9bfd3dfc-63de-4f7a-8717-dc0be23af0e7)

As we can see, new MFEM model with 4 spheres in air also increases quality of kCSD reconstruction! Maybe old model was just physically incorrect and was returning potentials which where not even removely similar to free space solution?

**Comment by mdovgialo** [comment]
Trying to calculate a dipole in 4 spheres using 10-05 electrodes:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/a4f04130-b116-44d8-8adb-cc5af6e45d58)

Ground Truth:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/2734f452-1adb-496a-ab9a-cb54aaf4deb2)

Potential (MFEM 4 shperes in air):

![image](https://github.com/Neuroinflab/kESI/assets/6193380/225c9538-d806-445a-9313-9405224f8e46)

Used a brain mask:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/41a29a47-a736-4cf9-b0c9-df78710d79fd)

kCSD solution:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/61a31355-20c4-4064-9933-7767c903e2b6)

kESI solution:

![image](https://github.com/Neuroinflab/kESI/assets/6193380/d655802d-d45f-40ed-ac9e-617f0d51015c)

They are almost exactly the same, there is small differences in values, but in range of a few percent.

The eigenvectors also look exactly the same:


[10-05_eigenvectors.mkv.webm](https://github.com/Neuroinflab/kESI/assets/6193380/cd2c895c-3955-4ff5-b051-e1056b79341d)

R_init for the basis sources is 0.03 meters - around the average distance between closest electrodes

Also we can see that we cannot detect any deep sources with this setup.

There might be an issue with my code, or my understanding how to use kESI...
 Or maybe the shperes are just homogenous enough??

**Comment by mdovgialo** [comment]
Found an issue with kESI in scalp! correction varies depending on the depth! Details in #20 . tl;dr if electrodes are too shallow in the scalp correction becomes spherically symmetrical, basically becomes kCSD solution.
